name: Public SSH Debug Session

on:
  workflow_dispatch:  # 手动触发

jobs:
  ssh-debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start SSH session with tmate
      uses: mxschmitt/action-tmate@v3

    - name: Keep session alive
      run: |
        echo "SSH 会话已启动，等待连接..."
        sleep 12h
